// THE DEMO GATE, AROUND THE WHOLE COUNTER — the host of the totem is as protected as every other host of
// this instance.
//
// ★ IT IS MOUNTED HERE BECAUSE THIS APP OWNS ITS LAYOUT. The kit ships the machinery (the dismissal cookie,
// the two Server Actions, the "cover the page, never redirect" shape) and the reference storefront's layout
// wires it; the totem is a fork that does not use those layouts, so it wires the same machinery itself. See
// `lib/gate/registry.tsx` for why the registry entry is written by hand rather than generated by the oven.
//
// The three degrades are the kit's, kept identical: no app filling the slot → the counter renders; an app
// filling it that this build cannot render → the counter renders; otherwise the cookie decides between the
// full-screen interstitial and the ribbon underneath.

import { dismissGate, reopenGate } from '@forgeco/storefront-kit/gate/actions';
import type { ReactNode } from 'react';
import { gateState } from '@/lib/gate/mount';

export async function GateWrapper({ children }: { children: ReactNode }) {
  const state = await gateState();

  if (state.show === 'interstitial') {
    const { Interstitial } = state.gate;
    return <Interstitial store={state.store} dismiss={dismissGate} />;
  }

  if (state.show === 'ribbon') {
    const { Ribbon } = state.gate;
    return (
      <>
        {children}
        {Ribbon ? <Ribbon store={state.store} reopen={reopenGate} /> : null}
      </>
    );
  }

  return <>{children}</>;
}
