// GENERATED by @forgeco/surface-codegen from composition.json — do not edit.
// It is DERIVED from this project's own composition, by a tool this project runs. Add or remove an app in
// composition.json and run `npm run codegen`; `npm test` fails while this file disagrees with
// that list, which is how you find out before a visitor does.
// The storefront half: the public URL "/feeds/google.xml", served by app "feed".

import { injectProductPath, injectReadBaseUrl, injectReadFace, injectRequestOrigin, injectRevalidateSeconds, injectStoreForHost } from '@/lib/extensions/route-injections';
import { GET as handler } from '@forgeco/ext-feed/routes/google-xml';

export const GET = (request: Request): Promise<Response> =>
  handler(request, {
    productPath: injectProductPath,
    readBaseUrl: injectReadBaseUrl,
    readFace: injectReadFace,
    requestOrigin: injectRequestOrigin,
    revalidateSeconds: injectRevalidateSeconds,
    storeForHost: injectStoreForHost,
  });
