// GENERATED by @forge/codegen from extensions/composition.base.json — do not edit.
// The storefront half: the public URL "/feeds/google.xml", served by app "feed".
// Adding an app here by hand is a red build (codegen drift); importing a listed app outside a generated
// file is a red build (scripts/composition/composition-imports.guard.test.ts). Take an app OUT by removing
// its entry from the list and running `pnpm codegen` — nothing else knows its name.

import { GET as handler } from '@forgecommerce/ext-feed/routes/google-xml';
import {
  injectProductPath,
  injectReadBaseUrl,
  injectReadFace,
  injectRequestOrigin,
  injectRevalidateSeconds,
  injectStoreForHost,
} from '@/lib/extensions/route-injections';

export const GET = (request: Request): Promise<Response> =>
  handler(request, {
    productPath: injectProductPath,
    readBaseUrl: injectReadBaseUrl,
    readFace: injectReadFace,
    requestOrigin: injectRequestOrigin,
    revalidateSeconds: injectRevalidateSeconds,
    storeForHost: injectStoreForHost,
  });
