// Typed access to the generated storefront UI catalog manifest — the theme's chrome inventory. The manifest
// is GENERATED by `pnpm codegen` (scanner in packages/codegen/src/ui-catalog.ts, buildStorefrontCatalogIR)
// and drift-checked in CI — never hand-edited. This module just shapes the raw JSON and adds a couple lookups.

import manifest from './generated/catalog.manifest.json';

export type CatalogVariant = { name: string; values: string[] };
export type CatalogProp = { name: string; type: string; optional: boolean };
export type CatalogCategory = 'primitives' | 'blocks';

export type CatalogComponent = {
  id: string;
  name: string;
  category: CatalogCategory;
  path: string;
  client: boolean;
  examplesExport: string;
  variants: CatalogVariant[];
  baseTypes: string[];
  props: CatalogProp[];
  tokens: string[];
};

export const COMPONENTS: CatalogComponent[] = (manifest as { components: CatalogComponent[] })
  .components;

export function findComponent(id: string): CatalogComponent | undefined {
  return COMPONENTS.find((c) => c.id === id);
}

/** Case-insensitive filter over name / id / path — the gallery's simple search. */
export function filterComponents(q: string | undefined): CatalogComponent[] {
  const needle = (q ?? '').trim().toLowerCase();
  if (!needle) return COMPONENTS;
  return COMPONENTS.filter((c) => `${c.name} ${c.id} ${c.path}`.toLowerCase().includes(needle));
}
