// ⛔ GENERATED by `node bin/gate-faces.mjs --write` from seed/box.json. DO NOT EDIT.
//
// The hub's destinations — one card per store, one row per tenant admin. This file exists because
// `apps/demo-gate` is baked into the kernel image ALONE (bin/build-local.sh rsyncs this directory and
// nothing else of the box), so the screen cannot read the declaration it is derived from. The guard that
// keeps the two identical is `bin/gate-faces.guard.mjs`.
//
// `host`/`env` are `null` for a face `seed/box.json` declares NO address for. That is carried rather
// than dropped: a destination the hub cannot address is one the visitor must be told about.

/** One destination of the hub. */
export type GateFace = {
  /** `<tenant>/<store handle>` for a shop, `<tenant>/admin` for an admin. The key the copy is written against. */
  key: string;
  kind: 'shop' | 'admin';
  tenant: string;
  /** The store's handle, or `null` for a tenant's admin. */
  store: string | null;
  /** The hostname this box publishes the face at, or `null` when it declares none. */
  host: string | null;
  /** The variable seed/box.json names to carry that hostname to the edge, or `null`. */
  env: string | null;
};

/** One card of the hub: a tenant, and the faces it publishes, in declaration order. */
export type GateTenant = { id: string; name: string; faces: GateFace[] };

export const GATE_TENANTS: GateTenant[] = [
  {
    "id": "forgeco",
    "name": "Forge",
    "faces": [
      {
        "key": "forgeco/forge",
        "kind": "shop",
        "tenant": "forgeco",
        "store": "forge",
        "host": "store.forgecommerce.pro",
        "env": "FORGE_DOMAIN"
      },
      {
        "key": "forgeco/outlet",
        "kind": "shop",
        "tenant": "forgeco",
        "store": "outlet",
        "host": "outlet.store.forgecommerce.pro",
        "env": "FORGE_OUTLET_DOMAIN"
      },
      {
        "key": "forgeco/admin",
        "kind": "admin",
        "tenant": "forgeco",
        "store": null,
        "host": "admin.store.forgecommerce.pro",
        "env": "FORGE_ADMIN_DOMAIN"
      }
    ]
  },
  {
    "id": "forgecafe",
    "name": "Forge Café",
    "faces": [
      {
        "key": "forgecafe/cafe",
        "kind": "shop",
        "tenant": "forgecafe",
        "store": "cafe",
        "host": "cafe.forgecommerce.pro",
        "env": "FORGE_CAFE_DOMAIN"
      },
      {
        "key": "forgecafe/balcao",
        "kind": "shop",
        "tenant": "forgecafe",
        "store": "balcao",
        "host": "totem.cafe.forgecommerce.pro",
        "env": "FORGE_TOTEM_DOMAIN"
      },
      {
        "key": "forgecafe/admin",
        "kind": "admin",
        "tenant": "forgecafe",
        "store": null,
        "host": "admin.cafe.forgecommerce.pro",
        "env": "FORGE_CAFE_ADMIN_DOMAIN"
      }
    ]
  }
];

/** Every face, flat — what the screen counts and what its test holds against seed/box.json. */
export const GATE_FACES: GateFace[] = GATE_TENANTS.flatMap((tenant) => tenant.faces);
